### ISSUE TITLE
[sui-studio] Infinite loop installing dependencies

### ISSUE THREAD

**Issue by julian-gernun** [SUI-Components/sui#106]
### Package

sui-studio@4.21

### Description

It keeps on reinstalling the dependencies over and over again

### Steps to Reproduce

1. run `npm run phoenix`

**Expected behavior:** It should install all dependencies and finish its execution.

**Actual behavior:** It installs the dependencies over and over again.

**Reproduces how often:** Only if an empty folder is in the sui-studio components folder

### Additional Information

**Temporary fix** You can avoid this issue by removing all empty folders in the repo, to find them run `find . -type d -empty`

**Comment by davidbarna** [comment]
It's doesn't seem to be a problem of sui-studio.
The problem is the postinstall https://github.com/SUI-Components/sui-components/blob/master/package.json#L17

Still worth the try to fix it.

**Comment by davidbarna** [comment]
The postinstall was removed from monorepo as bad practice.
