### ISSUE TITLE
[babel-preset-sui] env preset

### ISSUE THREAD

**Issue by davidbarna** [SUI-Components/sui#122]
### Package

[babel-preset-sui]@latest

### Description

Use env preset instead of plugins
Modifie browsers config according to SUI requirements

**Comment by carlosvillu** [comment]
To use Env, we need a browser support matrix defined isnt ?!

**Comment by davidbarna** [comment]
We'll apply fotocasa matrix. I'll ask them.
Basically latest chrome and firefox, IE11. In case of doubt we'll be restrictive. It can't be more restrictive than what we already have.
