### ISSUE TITLE
[sui-dashboard] Possibility to extract only a Major Version in SUI DASHBOARD

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/sui#1319]
### Package

@s-ui/dashboard@1

### Description

The current script `npx @s-ui/dashboard components – -v` outputs the complete version for each component

`v1.2.0`

It is cool but, in order to compare easily if a relevant major change has been introduced, it would be handy to have the option to extract just the major version

`v1`

Thanks!

### Steps to Reproduce

1. run `npx @s-ui/dashboard components -v`

**Comment by rmoralp** [comment]
Request accepted
