### ISSUE TITLE
[sui-lint] Add prettier config to format our code automatically

### ISSUE THREAD

**Issue by miduga** [SUI-Components/sui#138]
### Description

We would like to add prettier to our sui-lint in order to format our code automatically based on our linter config rules, so all developers improve development time.

### Additional Information

The implementation should be totally transparent for the user so he shouldn't notice any change but the advantatge of gettign automatically the code formatted before passing the linter, so it gets fixed before even he notice it.

https://github.com/prettier/prettier

**Comment by davidbarna** [comment]
sui-lint will execute a merge of prettier rules and current sui-lint rules 
Add a command `sui-lint format` that executes prettier and `es-lint --fix`
