### ISSUE TITLE
[sui-i18n] Move external dependency to package

### ISSUE THREAD

**Issue by rmoralp** [SUI-Components/sui#1468]
### Package

@s-ui/i18n

### Description

This package has `node-polyglot@0.4.3` as a dependency.
This version size is about 2.3kB minified

Given latest node-polyglot version (2.4.2) size is about 35.5kB minified
And current version achieve all our requirements
Then we have decided to move `node-polyglot@0.4.3` code to  `@s-ui/i18n` package and maintain this code.

### Additional Information

This task is not only about moving code to our package, we want to **keep our code style** and also **cover it with tests**

**Comment by theonly1me** [comment]
@rmoralp Can you please assign me this issue?
