### ISSUE TITLE
[sui-mono] `refactor` commit type should trigger new version of package

### ISSUE THREAD

**Issue by rmoralp** [SUI-Components/sui#1478]
### Package

@s-ui/mono@2

### Description
`refactor` commits does not trigger new versions of packages.
This has caused some problems in the past, so we want that `refactor` commit type triggers a release when checking for a release using `sui-mono check`.

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]

1. Make `refactor` a commit
2. Use `sui-mono check`
3. A new minor version of that package should be released

**Actual behavior:** [What actually happens]

1. Make `refactor` a commit
2. Use `sui-mono check`
3. We see a log `Nothing to release according to your recent commits.`

**Comment by andresin87** [comment]
Top!

**Comment by rmoralp** [comment]
Great Job @jordevo
