### ISSUE TITLE
[sui-studio] Put correct links on the home of SUI (https://sui-components.vercel.app/)

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/sui#1480]
### Package

[sui-studio]

### Description

Put correct links and simplified structure on the home of SUI (https://sui-components.vercel.app/)

**Expected behavior:** [What you expect to happen]

![expected](https://user-images.githubusercontent.com/23620759/193875238-52055331-4f54-4b0f-b110-598f73e2beb2.png)

**Actual behavior:** [What actually happens]

![current](https://user-images.githubusercontent.com/23620759/193875270-639de2aa-89ff-4ff3-9839-00548601deb4.png)

**Comment by andresin87** [comment]
the project is [sui-components](https://github.com/SUI-Components/sui-components) and the file to tackle this issue is [this one](https://github.com/SUI-Components/sui-components/blob/master/components/README.md)

**Comment by turolopezsanabria** [comment]
👏🏼 thnx!
