### ISSUE TITLE
🪲 The last items of the sidebar menu are unreachable

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/sui#1501]
### Package

@sui-studio

### Description

The last items of the sidebar menu are unreachable because there's no padding between the last element and the container

![221004 - Menu items are unreachable](https://user-images.githubusercontent.com/23620759/195999440-73713d24-50b0-455b-b32e-3ea7fc9dfe88.png)

### Steps to Reproduce

1. Grab a mobile device (I've used an iPhone)
2. Go to [sui-components.vercel.app](https://sui-components.vercel.app/)
3. Scroll the menu to the bottom
4. Try to select `primitive-injector`

**Expected behavior:** [What you expect to happen]

The menu items should always be reachable

### Additional Information

To fix it: Adjust the height of `.sui-Studio-sidebar`

❌ 100vh
✅ 100vh - height of .sui-Studio-navHeader (48px)

Also, please double the padding-bottom of the menu

❌ 16px
✅ 32px

**Comment by ays14** [comment]
hey @turolopezsanabria , let me take this up.

**Comment by turolopezsanabria** [comment]
sure @ays14! Assigned to you

Sorry the link was wrong, this is the right one: https://sui-components.vercel.app/
thnx

**Comment by ays14** [comment]
Thanks for the correct link, I will get started on this.

**Comment by ays14** [comment]
@turolopezsanabria I have opened a PR (attached above) for the fix. Please review.
