### ISSUE TITLE
The sidebar scrolling area does not show the last items

### ISSUE THREAD

**Issue by andresin87** [SUI-Components/sui#1520]
### Package

@s-ui/studio@11.28.0

### Description

The sidebar scrolling area does not show the last items

[Description of the issue]

### Steps to Reproduce

1. open any studio deployment
2. scrolldown the sidebar
3. you can't see the last items

**Comment by turolopezsanabria** [comment]
duplicated here?
https://github.com/SUI-Components/sui/issues/1501
