### ISSUE TITLE
[sui-domain] Research the possibility of use decorators to avoid boilerplate

### ISSUE THREAD

**Issue by carlosvillu** [SUI-Components/sui#164]
```

import {config, logger, performance} from '@s-ui/domain'

@logger
@config
@performance
export default class HTTPUserRepository {
  current () {
    this._log('start request')
    this._config().get()
  }
}
```

**Comment by carlesnunez** [comment]
Id they are going to implement this decorators always why not use simple inheritance? I mean HTTPUserRepository extends from Repository and respository owns the config, logger and performance... Even inside the Repository object you could use decorators for the re-usable.

Doing in this way you’ll reduse the boilerplate in a clean way than adding X decorators for each thing that you wan’t to inherit. It’s just an opinion, what do you think?
