### ISSUE TITLE
[sui-lint] no-unused-expressions rule should be treated as 'warning' instead of 'error'

### ISSUE THREAD

**Issue by rafamarquezv** [SUI-Components/sui#175]
### Package

sui-lint @ ^2.3.0

### Description

In our ES6 project, we are using 'chai' with 'expect' as follows:

`
expect(adRequestFactoryMockSpy.calledOnce, 'adRequestFactory method should be called once').to.be.true
`

When we launch our lint task (using sui-lint) error log entry appears for each use of 'expect' in every test, as follows:

`
   64:11  error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  `

**Expected behavior:** 
Use of 'expect' clause in test files should not be treated as an error.

**Actual behavior:** 
Use of 'expect' clause in test files is treated as an error: no-unused-expressions.

**Reproduces how often:** 
Always.

### Additional Information

To avoid this behavior we are using the following header in every test file:

`/* eslint-disable no-unused-expressions */`

**Comment by rafamarquezv** [comment]
Have a look at this plugin: https://www.npmjs.com/package/eslint-plugin-chai-friendly

**Comment by miduga** [comment]
#PR opened: https://github.com/SUI-Components/sui/pull/178

**Comment by rafamarquezv** [comment]
Thank you!!! :)
