### ISSUE TITLE
Accessibility linter

### ISSUE THREAD

**Issue by jcger** [SUI-Components/sui#191]
We need to integrate an accessibility linter for our jsx code

To be discussed:
- Should we use https://www.npmjs.com/package/eslint-plugin-jsx-a11y or is there a better module?
- Should the linter throw errors or warnings? (it would be nice if the rules would throw errors for the sui-components defined by UX to ensure their accessibility)

**Comment by miduga** [comment]
As right now is so hard to determine when errors are needed, I would keep them as warnings unless is a very wrong missing piece. :D

**Comment by midudev** [comment]
This was already implemented :)
