### ISSUE TITLE
[sui-test] Test package

### ISSUE THREAD

**Issue by julian-gernun** [SUI-Components/sui#196]
We need to wrap the whole test environment in one package in order to make it reusable for those developers that wants to add tests to her/his project

**Comment by naxhh** [comment]
In MT we have a test lib that allows running the same test code in server/frontend with 2 descriptors for server only or frontend only.

I think carlos used it also for vibbo? But not sure if he migrated it here or somewhere

Or do you refer to something else?

**Comment by julian-gernun** [comment]
@naxhh I guess it would be part of the package

**Comment by carlesnunez** [comment]
The thing is that for now we have at least one repo that is implementing their test in the test/browser test/server way. How is going to be managed the test path by the package?
