### ISSUE TITLE
[sui-widget-embeder] Create a sui-widget-embedder generate

### ISSUE THREAD

**Issue by carlesnunez** [SUI-Components/sui#213]
### Package
sui-widget-embeder
### Description
Create a widget files generator
#### Add a sui-widget-embeder generate command:
To avoid copy/paste errors and loose time on creating boilerplate could be useful if we have a generator similar to the one that we have on sui-studio.

**Should create the next folder and files on run:
 `sui-widget-embeder generate <widgetName> --widgetRegExpIdentifier='<regexp>'`**
1 . Create a folder called **<widgetName>**
2. Create a index.js file which must contain:
 ```javascript
import React from 'react'
import Widget from '@s-ui/widget-embedder/react/Widget'
import Widgets from '@s-ui/widget-embedder/react/Widgets'
import render from '@s-ui/widget-embedder/react/render'
import './index.scss'

const bootstrap = async () => {
  const {domain, i18n} = await setupDomainAndGeti18n()
  render(
    <Widgets>
      <Widget i18n={i18n} domain={domain} node='<nodename>'>
        {/*YOUR COMPONENT GOES HERE*/}
      </Widget>
    </Widgets>,
    'global'
  )
}

bootstrap()

```
3. Create an `index.scss` that must contain:
```sass
@import '~@schibstedspain/<sitePrefix-theme>-theme/lib/index.scss';
```

4. Create a `package.json` version that must contain:
```json
{
  "version": "1.0.0",
  "private": true,
  "pathnameRegExp": "<widgetRegExpIdentifier>"
}
```

**Comment by carlesnunez** [comment]
@carlosvillu @miduga

**Comment by carlosvillu** [comment]
OK for me.

**Comment by miduga** [comment]
👍
