### ISSUE TITLE
[sui-domain] Create new `listen` method that's the same $.execute.subscribe functionality

### ISSUE THREAD

**Issue by midudev** [SUI-Components/sui#214]
In order to improve the weird API signature, I'm proposing creating two new methods easier to understand and use.

Before:
```
this._domain.get('generate_search_url_search_use_case').$.execute.subscribe(({params, result}) => {
  const [generateUseCaseParams] = params
})
```

The proposed new API would be this one:
```
const listener = this._domain.get('generate_search_url_search_use_case').listen(({ params, response }) => {
 // params is already the used params for calling the useCase, no transformation needed
})
listener.stop()
```

Also, instead of having a decorator for this, I would do that on the s-ui/domain so you could listen any useCase no matter if it's being streamified in order to simplify the system.

**Comment by davidbarna** [comment]
+1

**Comment by carlosvillu** [comment]
We are talking of change the public API expose by the decorator, isn`t ?!

I mean w/out touch the domain code.

How do you will manage the breaking change in the components ?!

**Comment by carlesnunez** [comment]
Could you maintain the two ways with a deprecation message on the old one and remove it on a future step?

**Comment by miduga** [comment]
@carlesnunez @carlosvillu @davidbarna  The idea would be:

- Keep compatibility with the actual API and show a deprecation notice in the console ONLY in non-production environment.
- Stop using sui-decorator and make it inherent of @s-ui/domain

**Comment by carlosvillu** [comment]
What do you mean, make it inherent of ?!

**Comment by miduga** [comment]
I mean that all use_cases are by definition available to be listened. So, no need to use the s-ui decorator on each execute method. So @s-ui/domain make it for you, giving you a `listen` method along with the `execute` that will do the same functionality.

**Comment by carlesnunez** [comment]
This sounds great so if I can 'subscribe' to any use-case execution indeed I am winning flexibility to implement it

**Comment by carlosvillu** [comment]
I don`t know, That look like we are building a "framework agnostic" library in the domain using sui-domain like our "Domains Frameworks" ?!

I like the idea of use sui-domain to avoid boilerplate code. But that is another different thing. We do a lot of this with the AnemicModel.

**Comment by miduga** [comment]
The problem was that you had to create a streamify manually on your execute methods on the domain causing two things:
- Lack of maintanibility, as you had to adding/remove manually it when using/stop-using it.
- Lack of predictability, as you don't know if already a use_case could be listened while developing so you have to check it to be sure.
