### ISSUE TITLE
[sui-html-tagger] CI tests failing

### ISSUE THREAD

**Issue by jcger** [SUI-Components/sui#244]
### Package

sui-html-tagger@1.1.0

### Description

```
Firefox 59.0.0 (Mac OS X 10.12.0): Executed 60 of 61 (2 FAILED) (skipped 1) (3.248 secs / NaN secs)
TOTAL: 2 FAILED, 58 SUCCESS


1) should tag correctly a div specified in the tags list
     Tagger
     uncaught exception: AssertionError: expected null to equal 'c_tracking_tag' (:0)

2) should tag correctly elements specified in the tags list
     Tagger
     uncaught exception: AssertionError: expected null to equal 'c_tracking_button' (:0)

```
### Steps to Reproduce
From the sui root execute

`npm run test:ci`

### Additional Information

Only tested with firefox@59.0.0

**Comment by miduga** [comment]
Hi @jcger I'm not able to reproduce it. Could you please confirm if that's still happening?

![image](https://user-images.githubusercontent.com/1561955/39579605-75562116-4ee7-11e8-9e40-1fc6ffcbeb45.png)

![image](https://user-images.githubusercontent.com/1561955/39579627-7fa588fa-4ee7-11e8-884e-f91e8ef52654.png)

**Comment by jcger** [comment]
Hi @miduga, yep, I run it thrice and one the first run:

```
1) should tag correctly elements added later in the dom
     Tagger
     uncaught exception: AssertionError: expected null to equal 'c_tracking_dynamic' (:0)
```

second run and third run:
```
1) should tag correctly a div specified in the tags list
     Tagger
     uncaught exception: AssertionError: expected null to equal 'c_tracking_tag' (:0)

2) should tag correctly elements specified in the tags list
     Tagger
     uncaught exception: AssertionError: expected null to equal 'c_tracking_button' (:0)
```

I'm using firefox@59, node@8.9.4, npm@3.10.10 and running the `npm run test:ci` command
