### ISSUE TITLE
[sui-studio] Shall we run npm install after generating a component?

### ISSUE THREAD

**Issue by davidbarna** [SUI-Components/sui#28]
Issue from previous repo
https://github.com/SUI-Components/SUIStudio/issues/19

**Comment by julian-gernun** [comment]
+1

**Comment by davidbarna** [comment]
I would put it as an option. Then you can create your "npm run generate" with that option if you want.

**Comment by julian-gernun** [comment]
Can you think of any use case in which you wouldn't want to install after creating it?
