### ISSUE TITLE
[sui-ssr] Not compatible with sui-bundler version under 3

### ISSUE THREAD

**Issue by carlesnunez** [SUI-Components/sui#296]
sui-ssr@latest

### Description

Is mandatory to use sui-ssr with sui-bundler >= 3. Otherwise it will break [here](https://github.com/SUI-Components/sui/blob/master/packages/sui-ssr/server/ssr/index.js#L94) due to a spread operator usage on object.

### Actions to do

I think that there's no actions that we can do here. As long as we are not including sui-bundler on our sui-ssr package.

Maybe we must include sui-bundler >=3 as a dependency of the sui-ssr?

**Comment by miduga** [comment]
Is it confirmed that it works correctly with @s-ui/bundler@3?

**Comment by carlesnunez** [comment]
I've switched from bundler@2 to @3 and worked fine

**Comment by carlesnunez** [comment]
I'll close it until I make tests with clean environments in depth to be sure about if is an environment problem or is a problem with the bundler itself 😞
