### ISSUE TITLE
[sui-ssr && sui-react-initial-props] Always re-rendering once navigate between routes.

### ISSUE THREAD

**Issue by carlesnunez** [SUI-Components/sui#299]
It is more a problem with loadPage than with sui-ssr itself but assuming that loadPage is strictly attached to an ssr environment I associated it with ssr.
ssr@latest
react-initial-props@latest

### Description

react-router **is re-rendering its pages always** that we navigate due to a change-ref problem.

I realised about the problem when I've tried to navigate from one route to a nested one. 

For example let's imagine that we have this route scenario:

```javascript
  <Router>
    <Route path="/creditos/auto-renueva" getComponent={LoadAutoRenewPage}>
      <Route path="alertas" getComponent={LoadAlertsPage} />
    </Route>
  </Router>
```

And the next interaction scenario:
1. Lets say the user enters the app at `/creditos/auto-renueva`.

    | Component | Lifecycle Hooks *expected* | Lifecycle Hooks *called*
    |-----------|------------------------| ------------------------|
    | LoadAutoRenewPage | (1) `componentDidMount` | (1) `componentDidMount` |
    | LoadAlertsPage | N/A | N/A |

2. Now they navigate from `/creditos/auto-renueva` to `/creditos/auto-renueva/alertas`

    | Component | Lifecycle Hooks *expected* | Lifecycle Hooks *called*
    |-----------|------------------------| ------------------------|
    | LoadAutoRenewPage | (1) `componentWillReceiveProps `, (3) `componentDidUpdate` | (2) `componentDidMount` |
    | LoadAlertsPage | (2) `componentDidMount` | (1) `componentDidMount`

**What should happen**
- `LoadAutoRenewPage` should get `componentWillReceiveProps` and `componentDidUpdate` because it
    stayed rendered but just received new props from the router (like:
    `children`, `params`, `location`, etc.)
- `LoadAlertsPage` is mounted for the first time.

**What's happening**
- `LoadAutoRenewPage` is mounted for the ~first time~
- `LoadAlertsPage` is mounted for the first time.

More info on react-router v3 component mounting lifecycle [here](https://github.com/ReactTraining/react-router/blob/v3/docs/guides/ComponentLifecycle.md)

### Why is this happening?

Looking through the code I started trying to just do an async import without any usage of loadPages function.

Changing this:

```javascript
const LoadAutoRenewPage = loadPage(contextFactory, () =>
  import(/* webpackChunkName: "AutoRenueva" */ './pages/credits/AutoRenew')
)
const LoadAlertasPage = loadPage(contextFactory, () =>
  import(/* webpackChunkName: "Alertas" */ './pages/legal/alerts')
)

export default (
  <Router>
    <Route path="/creditos/auto-renueva" getComponent={LoadAutoRenewPage}>
      <Route path="alertas" getComponent={LoadAlertsPage} />
    </Route>
  </Router>
)
```

Into this:

```javascript
const LoadAutoRenewPage = () => import(/* webpackChunkName: "AutoRenueva" */ './pages/credits/AutoRenew').then(p => p.default)

const LoadAlertasPage = () => import(/* webpackChunkName: "Alertas" */ './pages/legal/alerts').then(p => p.default)

export default (
  <Router>
    <Route path="/creditos/auto-renueva" getComponent={LoadAutoRenewPage}>
      <Route path="alertas" getComponent={LoadAlertsPage} />
    </Route>
  </Router>
)
```

And it worked... so I was assuming that the problem was inside our loadPage function.

Getting into the function I could find that we return a function that once called will return the component in 3 different ways... Let's focus on the two that i've investigated in depth. The first one is happening in a normal way on the client:

### First trouble case:

You can check the file [here](https://github.com/SUI-Components/sui/blob/master/packages/sui-react-initial-props/src/withInitialProps.js#L8)

```javascript
    // create the context to be used as param on the getInitialProps
    // TODO: Maybe this is no needed as we already have created it?
    return contextFactory(createClientContextFactoryParams())
      // now, we have to create the Page to be rendered on the client with all the info
      .then(context => withInitialProps({ context, routeInfo })(Page))
```
This function is calling after all to the function `withInitialProps`.

Inside it the function will return another function that will return a Class definition that will curry the Page inside the first function call and use it inside the Class definition.

I'm not pretty sure about that but I think that the problem here is that we are Defining a new Class with a different reference each time that the route calls the `getComponent`function and, as a consequence call the withInitialProps too.

### Second trouble case:

Okay, so, I decided to comment this part of code and force our loadPage to move to the next case even if we were on client. The case were I wanted to be forced [is this one](https://github.com/SUI-Components/sui/blob/master/packages/sui-react-initial-props/src/loadPage.js#L37):

```javascript
const ServerPage = (props, { initialProps = {} }) =>
    <Page {...props} {...initialProps} />
```

Here the problem is very similar to the one that I've talked about earlier but what we are doing here is declare and ASSIGN an stateless component to a variable so... each time that our route call the getComponent function that is getted through the loadPage call it will REASSIGNATE a new ref to the ServerPage variable which is returned later and sended to the router, creating a component with a NEW REFERENCE  even if is exaclty the same than the other one. This will force an unmount of the old one and a mount of the new one.

### How I knew that this was a problem.

At this point I decided to move forward and dismiss also this case changing the logic at this point by another that will just return the Page component without currying or wrap it inside a function.

So... i've changed the this:

```javascript
  // we're in the server, so return just the component and pass the initialProps from the context
  const ServerPage = (props, { initialProps = {} }) =>
    React.cloneElement(Page, {...props, ...initialProps})
  // recover the initialProps if in the server we have retrieved them
  ServerPage.contextTypes = { initialProps: PropTypes.object }
  // detect if the page has getInitialProps and wrap it with the routeInfo
  // if we don't have any getInitialProps, just use a empty function returning an empty object
  ServerPage.getInitialProps = context => Page.getInitialProps({ context, routeInfo })
  // return the component to be used on the server
  return ServerPage
```

Into this(don't blame on me, I was just trying things 😆 ):

```javascript
  // // we're in the server, so return just the component and pass the initialProps from the context
  // const ServerPage = (props, { initialProps = {} }) =>
  //   React.cloneElement(Page, {...props, ...initialProps})
  // // recover the initialProps if in the server we have retrieved them
  // ServerPage.contextTypes = { initialProps: PropTypes.object }
  // // detect if the page has getInitialProps and wrap it with the routeInfo
  // // if we don't have any getInitialProps, just use a empty function returning an empty object
  // ServerPage.getInitialProps = context => Page.getInitialProps({ context, routeInfo })
  // // return the component to be used on the server

  return Page
```
And it worked. So, seems that is a 'ref' problem.

### Steps to Reproduce

1. Create a basic project with sui-ssr with two routes one nested inside the other
2. Create a page that have a console log inside the componentDidMount
2. Create a <Link /> from the top that goes to the nested (or the oposite, doesn't care)
4. Navigate and check how console.log behaves.

**Expected behavior:** [What you expect to happen]

We should have only one console.log on our console.

**Actual behavior:** [What actually happens]

We have one console log for each time that we navigate using the button (even if we are going to the same route)

**Reproduces how often:** (only for bugs) [What percentage of the time does it reproduce?]

Always

**Comment by carlesnunez** [comment]
I have done a kind of memoization just for the component and it seems to work.

I'd like to say that this is not obviously a final solution and must be checked for if it is a valid approach or we must look for another approach.

I've changed this:

```javascript
 export default (contextFactory, importPage) => (routeInfo, done) => {
   importPage()
     .then(createUniversalPage(contextFactory, routeInfo))
     .then(Page => { done(null, Page) })
 }
```

Into this

```javascript
export default (contextFactory, importPage) => {
  let PageUniversal
    return (routeInfo, done) => {
      if(!PageUniversal) {
        importPage().then(createUniversalPage(contextFactory, routeInfo)).then(Page => { 
            PageUniversal = Page
            done(null, PageUniversal)
        })
      } else {
        done(null, PageUniversal)
      }
    }
}
```

**Comment by miduga** [comment]
Could you try this PR in order to check if it fixes the problem? Further testing is needed in order to verify we're not breaking actual pages and how do we have to deal now with re-updates of the same page and child routes.

**Comment by carlesnunez** [comment]
I'm curious to know what was the resolution about this one? Did you find out a way of fixing it? 🤞
