### ISSUE TITLE
Usage of EntryPoint useCases

### ISSUE THREAD

**Issue by carlesnunez** [SUI-Components/sui#330]
Implementing EntryPoint I assumed that the config was injected by the EntryPoint automatically so I was defining my useCases in that way:

```javascript
const useCases = {
  get_seo_definition_by_path_use_case: SeoUseCasesFactory.getSeoDefinitionByPathUseCase
}
```

Then I realised that the useCase was not getting injected the config by the EntryPointFactory [check here](Components/sui/blob/b7d3477d040631b19ba9b05b9afc7cd0e60b4706/packages/sui-domain/src/EntryPointFactory.js#L34) as in fact is doing if we define it as an array (async import). [check here](https://github.com/SUI-Components/sui/blob/master/packages/sui-domain/src/EntryPointFactory.js#L46)

Is this an intended behavior? What's the point of not inject automatically the config if is a thing that we MUST do on every useCase definition?

@SUI-Components/manteiners

**Comment by davidbarna** [comment]
IMO doesn't make sense to add config automatically. We should have control on the deps to inject in each case.
