### ISSUE TITLE
[sui-studio] "npx sui-studio dev XXXX --link-package XXXX" provokes error on deploy

### ISSUE THREAD

**Issue by juanmaguitar** [SUI-Components/sui#374]
### Package

@s-ui/studio@5.16.0

### Description

The command `npx sui-studio dev molecule/buttonGroup --link-package ./components/atom/button` allows to work on the `MoleculeButtonGroup` component while using changes on `AtomButton` as if they have been released

Everything works fine until the code is deployed. When the code is deployed some dependencies need to be actually referenced to their "production" version.

For example, in `sui-components/demo/molecule/buttonGroup/demo/index.scss`

This will work locally if launched w/ `npx sui-studio dev molecule/buttonGroup --link-package ./components/atom/button` 
```
@import "@schibstedspain/sui-atom-button/index.scss";
```

but it will provoke an error on Travis when deployed. This line should actually be replaced by...
```
@import "~@schibstedspain/sui-atom-button/lib/index.scss";
```

So, there's some inconsistency in the DEVEL environment and the PROD environment that needs to be taken into account when using `--link-package`

**Comment by carlosvillu** [comment]
I think that this happen because you are using the "link version" without have used never the actual package comming from npm ?!

**Comment by carlosvillu** [comment]
Talking with Juanma, we see that the best to avoid this error in the future is add a warning in the sui-bundler when we found this kind of paths: `@import "@schibstedspain/sui-atom-button/index.scss";` and suggest this other path: @import "~@schibstedspain/sui-atom-button/lib/index.scss";

**Comment by carlesnunez** [comment]
So tu understand how the symlink works. If I import the lib version and I make change on the atom button... are the changes going to be 'rebuilded' and copied to de lib directory?
