### ISSUE TITLE
SSR to return the SPA in case of error

### ISSUE THREAD

**Issue by betobe** [SUI-Components/sui#432]
### Package

sui-ssr@2.11

### Description

To return the app file (index.html) with the corresponding error status as header and also as part of the app data, instead of reading and returning a 4xx|5xx.html file when an error occurs.
+ This would make the SPA capable of choosing what to do in case of any error (show a message; redirect to somewhere else; offer some other content).
+ Users would be able to continue using the app even in case of error.
+ Errors pages would be built as react components (as a regular page).
+ The need of "one file per error" and its maintenance would be removed.
+ Given that New Construction SPA works for different sites with a custom look and feel for each site ( and site-config identification is done by the SSR) this feature would make error pages to be compliant with each site brand look and feel straightforward.

⚠️  This change would not be backward compatible.

**Comment by carlosvillu** [comment]
Why dont you just copy your public/index.html to public/400|500.html ?!

**Comment by carlosvillu** [comment]
Or maybe you can use the hooks, to response what you want.

**Comment by betobe** [comment]
> Why dont you just copy your public/index.html to public/400|500.html ?!
> Or maybe you can use the hooks, to response what you want.

Although It might be possible to find a way of emulate what I need with a hook, it would be a workaround. I want to avoid workarounds with this proposal. What are your concerns about this approach?

**Comment by carlosvillu** [comment]
The main idea of sui-ssr is been 100% agnostic to the SPA. But NC SP/SSR are not agnostic anymore. I prefer to use a workaround for a specific project is that is able than change the generic behavior in the rest of the SPAs. 

about onstart-hook, I prefer to avoid fully extendable code, to be able to evolve the tools with the minimal risks.

**Comment by betobe** [comment]
Well, everything I've suggested (this proposal + open hooks) is in favor of agnosticity (plus benefits already listed in the proposal).

Also,
> The main idea of sui-ssr is been 100% agnostic to the SPA. But NC SP/SSR are not agnostic anymore.

I think It never has and it never will. SSR knows a lot about SPA and it is just fine. But I really don't understand why in your opinion NC case is not agnostic based on your definition of agnosticity and the rest of SPAs are indeed. Could you clarify this?

Let me explain myself. This is what I see (and it is a quick shallow list):

PROPOSAL + new hooks system:
**spa-knowing-ssr**:
- hooks implementation
- ~~xxx.html files~~ current

**ssr-knowing-spa**:
- spa's hooks implementation magic import
- spa's node_modules magic imports
- spa's index.html file
- ~~spa's xxx.html files~~ current
- ~~spa's public-env file~~ current
- ~~any kind of data for hydration~~ current (more complex but still in favor of agnosticity)

On the other hand, for the workaround you suggested I would need to create a hook with some code similar to what ssr/index.js already does. And if that's the case, we would half re-write an ssr process in a hook. I don't see it.

> about onstart-hook, I prefer to avoid fully extendable code, to be able to evolve the tools with the minimal risks.

Finally, I don't know what kind of risks you are talking about. An example would help me to understand. But I think that reducing responsibility from any package is the best riskless choice, always.
