### ISSUE TITLE
[i18n] Method to format currency number is throwing an error by default

### ISSUE THREAD

**Issue by AitorRodriguez990** [SUI-Components/sui#520]
### Package

i18n@latest

### Description

Using the method to format currency number is throwing an error by default.
https://github.com/SUI-Components/sui/blob/master/packages/sui-i18n/src/i18n.js#L64

### Steps to Reproduce

`i18n.c(20000)` returns:

![image](https://user-images.githubusercontent.com/13108014/53882859-ba90fb80-4017-11e9-8c35-fad97dda36db.png)

**Expected behavior:** Return number without any currency.

**Actual behavior:** Throw an error.

**Reproduces how often:** (only for bugs) Always.

**Comment by midudev** [comment]
Currency should be defined before using this method.

```
  set currency(currency) {
    this._currency = currency
  }
```

Anyway, maybe is a good idea to not break the code by default and just return the same value while giving a console.warn in the console.
