### ISSUE TITLE
[sui-mono] commiting changes

### ISSUE THREAD

**Issue by JoanClaret** [SUI-Components/sui#524]
### Package

@s-ui/mono@1.40.0

### Description

Hi there
i'm trying to install sui-mono in [motor literals repo](https://github.schibsted.io/scmspain/frontend-mt--module-i18n-literals). to do so, i've been adding the following  package.json dependencies :

```
  "devDependencies": {
    "@s-ui/mono": "1",
    "@s-ui/precommit": "2",
    "husky": "0.13.3",
    "jsonfile": "2.2.3",
    "validate-commit-msg": "2.12.2"
  }
```
the following config: 
```
"config": {
    "validate-commit-msg": {
      "types": "@s-ui/mono/src/types"
    },
    "sui-mono": {
      "packagesFolder": ""
    }
  }
```

and the scripts:

```
  "scripts": {
    "check": "node scripts/check.js",
    "check:release": "sui-mono check",
    "co": "sui-mono commit",
    "commitmsg": "validate-commit-msg",
    "dist": "node scripts/dist.js",
    "phoenix": "rimraf node_modules && npm i",
    "precommit": "sui-precommit run",
    "predist": "rm -rf dist && mkdir -p dist && touch dist/languages.json && npm run check",
    "prepublish": "npm run dist",
    "release": "sui-mono release",
    "release:check": "sui-mono check"
  }
```

since this package does not have an `src` folder, when i run `npm run co`, i get the following error:
`Error: ENOENT: no such file or directory, scandir '[...]frontend-mt--module-i18n-literals/src`

i guess that `"packagesFolder": ""` from `package.json` config was meant to solve this, but looks like i have something missconfigured.

can you guys help me on that?

### Steps to Reproduce

1. [First Step]
download or literals repo and open a new branch

2. [Second Step]
replace our scripts, config and devDependencies by this ones:

```
{
  "scripts": {
    "check": "node scripts/check.js",
    "check:release": "sui-mono check",
    "co": "sui-mono commit",
    "commitmsg": "validate-commit-msg",
    "dist": "node scripts/dist.js",
    "phoenix": "rimraf node_modules && npm i",
    "precommit": "sui-precommit run",
    "predist": "rm -rf dist && mkdir -p dist && touch dist/languages.json && npm run check",
    "prepublish": "npm run dist",
    "release": "sui-mono release",
    "release:check": "sui-mono check"
  },
  "config": {
    "validate-commit-msg": {
      "types": "@s-ui/mono/src/types"
    },
    "sui-mono": {
      "packagesFolder": ""
    }
  },
  "devDependencies": {
    "@s-ui/mono": "1",
    "@s-ui/precommit": "2",
    "husky": "0.13.3",
    "jsonfile": "2.2.3",
    "validate-commit-msg": "2.12.2"
  }
}
```
3. [step 3]
try to commit something by running `npm run co`

### Additional Information

looks like this is working for MA vertical, with `"@s-ui/mono": "^1.38.0"`
https://github.schibsted.io/scmspain/frontend-ma--module-i18n-literals/blob/master/package.json

**Comment by jcger** [comment]
looks like MA doesn't work either...

when `"packagesFolder": ""` the default packageFolder will be [`src`](https://github.com/SUI-Components/sui/blob/e7127492a6ade64438bbc0356a261ab922f4efb3/packages/sui-cz/config.js#L17) which seems to not exist. I guess using `"packagesFolder": "dictionaries"` will fix this

**Comment by jcger** [comment]
@JoanClaret can we close this?

**Comment by JoanClaret** [comment]
Solved, so closing
