### ISSUE TITLE
[sui-studio] Duplicated list of themes

### ISSUE THREAD

**Issue by desko27** [SUI-Components/sui#686]
### Package

sui-studio@7

### Description

For some reason, the following components are displaying a duplicated list of themes with path:

➡️ https://sui-components.now.sh/workbench/molecule/autosuggest/demo
➡️ https://sui-components.now.sh/workbench/molecule/select/demo

<img width="584" alt="Screenshot 2019-10-25 at 12 42 35" src="https://user-images.githubusercontent.com/4168389/67565299-5dbc8f80-f725-11e9-9583-40557ec461be.png">

**Comment by midudev** [comment]
This issue is going to be fixed with this PR: https://github.com/SUI-Components/sui/pull/723

**Comment by midudev** [comment]
Fixed!
