### ISSUE TITLE
[sui-domain] What to do with undefined properties on domain objects' representation?

### ISSUE THREAD

**Issue by jordevo** [SUI-Components/sui#858]
### Package

sui-domain@latest

### Description

Our current implementation of `.toJSON` for domain objects outputs all the object's properties even if their value is `undefined`. 

**Expected behavior:** I would expect properties with a value of `undefined` not to be returned.

**Actual behavior:** All properties, even those with a value of `undefined` are returned.

### Additional Information

Prior to any implementation, we should consider that this would most probably have side effects due to the extended use of `sui-domain` on several projects.

**Comment by carlosvillu** [comment]
I understand the difference between expected and actual behavior. But I'd like to understand what problems this difference is making for you.

Or is it just a theoretical issue?

**Comment by jordevo** [comment]
For instance, when it comes to testing, I think it's easier to have our expected objects "clean" of `undefined` properties so we can then assert them as deeply equal to the returned object, not having to do a bunch of expects for some properties. Does it make sense?
