### ISSUE TITLE
[sui-studio] Make it work locally

### ISSUE THREAD

**Issue by davidbarna** [SUI-Components/sui#9]
### Package

sui-studio@latest

### Description

To be able to migrate common deps to sui-studio, we need to make it work locally.

**When** sui-studio is executed
**Then** it should check is there is a local and/or global instance of it
**When** there is a local instance of the studio, 
**Then** it should warn the user it's using local version and do it
**Otherwise** it should throw error and ask user to `npm install sui-studio --save-dev`

**Comment by miduga** [comment]
Maybe we should separate the global `studio create` and the other studio commands. So the first is global, but the latter is only local.
